# Generated by Django 5.2.10 on 2026-02-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('car_brand', models.CharField(max_length=255)),
                ('car_model', models.CharField(max_length=255)),
                ('budgt', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
